### PR TITLE
Fix merging quote on configurable products

### PR DESCRIPTION
**Pull request by paco-shum**
Issue: 
When an abandoned cart contains configurable items, the original method won't be able to add the parent due to missing selected options on `$currentQuote->addProduct($item->getProduct());`
See screenshot as example
Screenshot 2023-02-09 at 18 59 06

Solution:
Using getAllVisibleItems() instead, and loop through visible items to check for simple products that are contained within a configurable product. This method is borrowed from the merge() function within Quote but slightly simplified to match the original implementation. 
(Currently this duplicate when adding the same configurable product but this can fixed by back step a bit on simplification and use  `if ($quoteItem->compare($item)` or similar instead)

actually now thinking,...why not just use the merge function on quote...ah I forgot why whoops

edit: We have confirmed it will indeed duplicate the item (not adding QTY) using this fix so need slight modification

### CODE REVIEW

**Comment by sta1r** [comment]
@paco-shum Thank you for this. We'll check it out and come back to you.

**Comment by pvpcookie** [comment]
Hi Paco, 

Would you be able to list out the steps you took to get to this point please, we have been struggling to recreate the issue you reported. 

When you refer to selected option are you refering to the Customizable options on the product ?

**Comment by paco-shum** [comment]
Hi @pvpcookie 
Thanks for getting back and sorry for the confusion, here are the steps I took to trigger that function
1. on browser A, add a configurable product to cart
2. then on browser B, add another configurable product to cart
3. on browser A, access {siteURL}/connector/email/getbasket/quote_id/{the quote created on step 2}/

The assumption
- the customer has added an item using a device e.g. phone added an item to the basket 
- the customer got an abandoned cart email and opened on another device e.g. desktop 
- the customer opened the email while they might have an item within the basket already (either from current the session or as a logged-in customer who has a cart saved)

I have just checked it again, the product is indeed a configurable product with child simple products (under the product -> 'Configurations' tab, not 'Customizable Options ') 

Hope this helps.
Kind regards,

**Comment by pvpcookie** [comment]
Hi @paco-shum 

Thank you this helps immensely, i will look further into this and get back to you.

**Comment by pvpcookie** [comment]
Hi Paco, 

Thanks for the patients and contribution it really appreciated, could you please direct you PR to the develop branch and we can a take it from there :)

**Comment by paco-shum** [comment]
@pvpcookie done

**Comment by paco-shum** [comment]
Hmm. 1 sec

**Comment by paco-shum** [comment]
@pvpcookie fixed. hope this is ok.

**Comment by pvpcookie** [comment]
Hi @paco-shum 

Perfect, thank you.

**Comment by paco-shum** [comment]
Hi @pvpcookie may I ask is there a timeline for this fix gets released to master/ view version? We have a merchant that would like to have this sorted. Thanks.

**Comment by paco-shum** [comment]
I think my fork/ local git is messing up, made a new PR to fix that. 
https://github.com/dotmailer/dotmailer-magento2-extension/pull/603

Thanks

**Pull request closed without merging**
