### PR TITLE
Bundling escape

### PR DESCRIPTION
**Pull request by adeelq**

### CODE REVIEW

**Comment by cdiacon** [comment]
ROI code tracking not working - js error

**Comment by adeelq** [comment]
@cdiacon can you paste JS error here please

**Comment by cdiacon** [comment]
screen shot 2017-06-22 at 12 49 28

**Comment by cdiacon** [comment]
feefo url changed the & to "&amp" 

http://www.feefo.com/feefo/feefologo.jsp?logon=dummylogon&amp
http://www.feefo.com/feefo/feefologo.jsp?logon=dummylogon&

**Pull request merged**
