### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by adeelq**

### CODE REVIEW

**Comment by cdiacon** [comment]
@adeelq 

__Magento throws exception if payment method does not exist #186__

One of the case that the payment is missing from order data is to manually truncate "sales_order_payment". Adding additional check with "getMethod" for will also fail.

You need to get to the source of the problem and should revert the change.

**Comment by adeelq** [comment]
@cdiacon Magento throws exception if payment method does not exist #186 In that it is ok for exception to be thrown. One should not truncate that table. However this should work fine if they removed the Payment Method extension from Magento.

**Comment by cdiacon** [comment]
@adeelq __updated contact's last quote id before sending campaign #181__

There is no chanse to get this updated in time before sending camapign - revert.

**Comment by cdiacon** [comment]
@adeelq What is this commit about https://github.com/dotmailer/dotmailer-magento2-extension/pull/184/commits/ba78ebfd2adaa2ae686d8b2b4705059b14692828 ?

**Comment by adeelq** [comment]
@cdiacon https://github.com/dotmailer/dotmailer-magento2-extension/pull/184/commits/ba78ebfd2adaa2ae686d8b2b4705059b14692828 is reload button to log reader. If you reading logs and after some time you want to reload the file again to see the changes

**Comment by cdiacon** [comment]
@adeelq this PR has too many issues for review - do not push any more changes, your current work should go into :

* separate PR for new changes
* different local/upstream branch where you create new PR from there

**Pull request merged**
