### PR TITLE
Fix null storeid

### LINKED ISSUE #512: Error when order has no store ID
I detected this case when running the M2 Integration Testsuite. 

The issue is with https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/Observer/Sales/SaveStatusSmsAutomation.php#L153 when it is called with a `NULL` value it throws an Exception that interrupts the save order process.

Here is the explanation:
When the order has no store ID, `$order->getStoreId()` returns `NULL` so `$storeId` is assinged `NULL`.
Then `$this->storeManager->getStore($storeId)` returns the default store so `$store` gets assigned a valid Store Object
Next, the call to `$appEmulation->startEnvironmentEmulation($storeId);` throws the exception because the original NULL assigned to $storeId is being used, but the algorithm already got a valid Store with its corresponding ID from the storeManager.

To reproduce the error simply install Magento 2 via composer, require this module and run `php bin/magento dev:tests:run integration`

### PR DESCRIPTION
**Pull request by barbazul**
Fixes #512

### CODE REVIEW

**Comment by barbazul** [comment]
I made the fix starting from master and then had to send the PR to develop because master is blocked apparently.

This caused a lot of "merge" commits to be added to the PR, instead of my single commit. 

If this proves to be too confusing to the reviewers, I can resend the PR starting from a develop branch

**Comment by simon-letch** [comment]
Hey @barbazul,

Thanks for the contribution!

We're in the middle of a sprint at the moment. Will try to squeeze in the review as part of this sprint, but if not it will get prioritised for next sprint.

Thanks,
Simon

**Comment by barbazul** [comment]
Awesome.

Good luck with your Sprint!!

**Comment by barbazul** [comment]
Hey guys. Any updates on this?

**Comment by adeelq** [comment]
@barbazul Any specific reason why changed from `$storeId` to `$store->getId()` 

`$storeId` comes from `$storeId = $order->getStoreId();` every order should have a store id. What is the reason you getting null value from `$order->getStoreId()`

**Comment by adeelq** [comment]
@barbazul Any specific reason why changed from `$storeId` to `$store->getId()` 

`$storeId` comes from `$storeId = $order->getStoreId();` every order should have a store id. What is the reason you getting null value from `$order->getStoreId()`

**Comment by adeelq** [comment]
@barbazul Any specific reason why changed from `$storeId` to `$store->getId()` 

`$storeId` comes from `$storeId = $order->getStoreId();` every order should have a store id. What is the reason you getting null value from `$order->getStoreId()`

**Comment by adeelq** [comment]
@barbazul Any specific reason why changed from `$storeId` to `$store->getId()` 

`$storeId` comes from `$storeId = $order->getStoreId();` every order should have a store id. What is the reason you getting null value from `$order->getStoreId()`

**Comment by adeelq** [comment]
@barbazul order should always have store id. any reason why you getting null value from order?

**Comment by adeelq** [comment]
@barbazul order should always have store id. any reason why you getting null value from order?

**Comment by adeelq** [comment]
@barbazul order should always have store id. any reason why you getting null value from order?

**Pull request merged**
